TICKER_TO_COMPANY = {
    # Indian large-caps (NSE)
    "RELIANCE.NS": "Reliance Industries",
    "HDFCBANK.NS": "HDFC Bank",
    "TCS.NS": "Tata Consultancy Services",
    "INFY.NS": "Infosys",
    "ICICIBANK.NS": "ICICI Bank",
    "SBIN.NS": "State Bank of India",
    "BHARTIARTL.NS": "Bharti Airtel",
    "WIPRO.NS": "Wipro",
    "DRREDDY.NS": "Dr Reddy's Laboratories",
    "TATASTEEL.NS": "Tata Steel",
    "LT.NS": "Larsen & Toubro",
    "HCLTECH.NS": "HCL Technologies",
    "ADANIPORTS.NS": "Adani Ports & SEZ",
    "TECHM.NS": "Tech Mahindra",
    "BAJAJFINSV.NS": "Bajaj Finserv",
    "PIDILITIND.NS": "Pidilite Industries",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "ASIANPAINT.NS": "Asian Paints",
    "MAHINDRA.NS": "Mahindra & Mahindra",
    "IOC.NS": "Indian Oil Corporation",
    "BEL.NS": "Bharat Electronics",
    "BPCL.NS": "Bharat Petroleum Corporation",
    "ONGC.NS": "Oil & Natural Gas Corporation",
    "COALINDIA.NS": "Coal India",
    "POWERGRID.NS": "Power Grid Corporation",
    "NTPC.NS": "NTPC",
    "JSWSTEEL.NS": "JSW Steel",
    "BAJAJAUTO.NS": "Bajaj Auto",
    "TITAN.NS": "Titan",
    "DMART.NS": "Avenue Supermarts (DMart)",
    "GAIL.NS": "GAIL India",
    "CIPLA.NS": "Cipla",
    "EICHERMOT.NS": "Eicher Motors",
    "SBILIFE.NS": "SBI Life Insurance",
    "INDUSINDBK.NS": "IndusInd Bank",
    "LTIM.NS": "LTIMindtree",

    # Global mega-caps (US & Intl)
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "NVDA": "NVIDIA",
    "GOOGL": "Alphabet (Google)",
    "AMZN": "Amazon",
    "META": "Meta Platforms",
    "BRK-B": "Berkshire Hathaway",
    "BRK.A": "Berkshire Hathaway A",
    "TSLA": "Tesla",
    "AVGO": "Broadcom",
    "ASML": "ASML Holding",
    "LLY": "Eli Lilly",
    "COST": "Costco",
    "ORCL": "Oracle",
    "XOM": "Exxon Mobil",
    "CVX": "Chevron",
    "COP": "ConocoPhillips",
    "SAP": "SAP SE",
    "NVO": "Novo Nordisk",
    "PM": "Philip Morris International",
    "CRM": "Salesforce",
    "BABA": "Alibaba Group",
    "AMGN": "Amgen",
    "C": "Citigroup",
    "HSBC": "HSBC Holdings",
    "TXN": "Texas Instruments",
    "INTU": "Intuit",
    "UNH": "UnitedHealth Group",
    "HD": "Home Depot",
    "CSCO": "Cisco Systems",
    "JNJ": "Johnson & Johnson",
    "PG": "Procter & Gamble",
    "BAC": "Bank of America",
    "WMT": "Walmart",
    "DIS": "Walt Disney",
    "KO": "Coca‑Cola",
    "PEP": "PepsiCo",
    "MCD": "McDonald's",
    "ADBE": "Adobe",
    "IBM": "IBM",
    "INTC": "Intel",
}
