TICKER_TO_COMPANY = {
    "RELIANCE.NS": "Reliance Industries",
    "TCS.NS": "Tata Consultancy Services",
    "HDFCBANK.NS": "HDFC Bank",
    "INFY.NS": "Infosys",
    "ICICIBANK.NS": "ICICI Bank",
    "SBIN.NS": "State Bank of India",
    "BHARTIARTL.NS": "Bharti Airtel",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "ITC.NS": "ITC",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "SUNPHARMA.NS": "Sun Pharma",
    "MARUTI.NS": "Maruti Suzuki",
    "AXISBANK.NS": "Axis Bank",
    "BAJFINANCE.NS": "Bajaj Finance",
    "WIPRO.NS": "Wipro",
    "POWERGRID.NS": "Power Grid Corporation",
    "NTPC.NS": "NTPC",
    "ONGC.NS": "Oil & Natural Gas Corporation",
    "COALINDIA.NS": "Coal India",
    "TATAMOTORS.NS": "Tata Motors",
    "TATASTEEL.NS": "Tata Steel",
    "AAPL": "Apple",
    "TSLA": "Tesla",
    "META": "Meta Platforms",
    "GOOGL": "Alphabet (Google)",
    "AMZN": "Amazon",
    "MSFT": "Microsoft",
    "NVDA": "NVIDIA",
    "JPM": "JPMorgan Chase",
    "V": "Visa",
    "MA": "Mastercard",
    "JNJ": "Johnson & Johnson",
    "PG": "Procter & Gamble",
    "BAC": "Bank of America",
    "WMT": "Walmart",
    "DIS": "Walt Disney",
    "KO": "Coca-Cola",
    "PEP": "PepsiCo",
    "MCD": "McDonald's",
    "ADBE": "Adobe",
    "INTC": "Intel",
    "IBM": "IBM",
    # Add more as needed
}